### ISSUE TITLE
Unable to load plugin 'picotmp_dummy' from 'picotmp_dummy/picotmp_dummy.php'

### ISSUE THREAD

**Issue by ghost** [bigicoin/PicoTooManyPages#1]
Dear Bigi, I'm trying to use PicoTooManyPages, but I've got an error and a blank page in my Pico. What have I lost?

`2019/08/19 10:13:17 [error] 723#723: *110 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Unable to load plugin 'picotmp_dummy' from 'picotmp_dummy/picotmp_dummy.php': File not found in /var/www/txt/vendor/picocms/pico/lib/Pico.php:639
Stack trace:
#0 /var/www/txt/vendor/picocms/pico/lib/Pico.php(520): Pico->loadLocalPlugins(Array)
#1 /var/www/txt/vendor/picocms/pico/lib/Pico.php(401): Pico->loadPlugins()
#2 /var/www/txt/index.php(39): Pico->run()
#3 {main}
  thrown in /var/www/txt/vendor/picocms/pico/lib/Pico.php on line 639" while reading response header from upstream, client: 192.168.0.149, server: txt.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "txt.local"`

**Comment by bigicoin** [comment]
Hi @saldacenkaw , apologies for that!

I haven't looked into it in detail, but judging by the error, it seems like it's trying to load a plugin named `picotmp_dummy` which is unintended. My quick guess is that a newer version of Pico has changed the behavior of reading folders so even an empty folder is assumed to be a plugin folder.

This plugin was written in early 2017, back in the Pico 1.0 days, so my guess is Pico 2.0 has changed significantly and this needs some work.

I haven't done anything with Pico in a couple of years and currently can't promise any time to work on fixes for it. Sorry about that!

**Comment by ghost** [comment]
Sorry for bother you with this,
